Milestone 2: Create interface
NtwaliHeritier/math-magicians pull request #2
Opened 2021-02-02 19:31 UTC by NtwaliHeritier

In this milestone,
- I created the four components
- I created a user interface

2021-02-02 20:37 UTC, christianotieno requested changes
## Changes required ♻️ 
Hello @NtwaliHeritier 👋 
Good job with the milestone so far. 👍 

There aren't many issues in this milestone as you have not deviated from the main objectives much. I am glad you are still in line the requirements and that you are determined to do everything right with this project. ⌛ 

Below 👇 are changes that touch on code restructuring, use of ES6 syntax in declaring functions and issues to do with default props. 

Kindly take a look and wor on the suggestions. Cheers!

### Happy coding 💻 
#### CHristian Otieno (CR)

2021-02-02 20:37 UTC, christianotieno commented on src/components/App.js
> +}
## Use ES6 Arrow function

- [ ] kindly implement this function component with the recommended with an ES6 arrow function.
```suggestion
const  App = () => {
  return (
    <>
      <Display result="0" />
      <ButtonPanel />
    </>
  );
}
```

2021-02-02 20:37 UTC, christianotieno commented on src/components/display.js
> +};
## Optional Change: Destructure this component 
- [ ] This `Display` component should have been restructured as inspired below. You will end up using elegant code, easy to read code and with fewer lines of code as well.
```suggestion
const Display = { (result) } => {
  return <h3>{result}</h3>;
};
```

2021-02-02 20:37 UTC, christianotieno commented on src/components/display.js
> +};
## Add default props in this component
- [ ] This display component should have the incoming prop which is the `result` as a String with default value = 0 ([should be String screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/validateAsString.png)) ([default props screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone2/display/DefaultProp.png))
```suggestion
Display.defaultProps = {
  value: "0"
};

Display.propTypes = {
  result: PropTypes.string,
};
```

2021-02-03 00:05 UTC, BrittanyBlake approved these changes
### Status: Approved ✅ 
****
### Hi @NtwaliHeritier ! 👋 
### Great job implementing the requested changes!! 🎖️ It's a 👍 from me! Go ahead and merge this pull request and keep up the good work 😄
****


 Good Luck and Happy Coding! 🍀 👩🏾‍💻

2021-02-03 00:11 UTC, merged